version: "3"

services:
  db:
    image: postgres
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=share-it
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - "./db/data:/var/lib/postgresql/data"